#!/usr/bin/env node
/**
 * Image optimization pipeline for TerraQura.
 *
 * Reads JPG sources from `images/`, generates WebP (and AVIF) at multiple
 * widths into `public/images/`, plus a tiny blur-placeholder JSON manifest.
 *
 * Output filenames follow `<slug>-<width>.webp` so Next/Image can pick the
 * right size for the device.
 *
 * Run:  node scripts/optimize-images.mjs
 */
import { readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve, parse } from "node:path";
import sharp from "sharp";

const ROOT = resolve(import.meta.dirname, "..");
const SRC_DIR = resolve(ROOT, "images");
const OUT_DIR = resolve(ROOT, "public/images");
const MANIFEST = resolve(ROOT, "src/lib/image-manifest.ts");

// Target widths. The widest you'd ever render an image is full-bleed hero,
// then mid-section feature, then small card / decorative.
const WIDTHS = [640, 1024, 1600, 1920];
const WEBP_QUALITY = 78;
const AVIF_QUALITY = 60; // AVIF compresses ~30% better than WebP at same perceived quality
const BLUR_WIDTH = 16; // for low-quality placeholder data URL

mkdirSync(OUT_DIR, { recursive: true });

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/\.(jpe?g|png)$/i, "")
    .replace(/=/g, "")              // typo correction (e.g. "mu=ission")
    .replace(/(\w+)anance/g, "$1anence") // "permanance" -> "permanence"
    .replace(/(\w+)oncahin/g, "$1onchain") // "oncahin" -> "onchain"
    .replace(/(\w+)cahin/g, "$1chain")   // "cahin" -> "chain"
    .replace(/aduit/g, "audit")
    .replace(/regualtor/g, "regulator")
    .replace(/fusioj/g, "fusion")
    .replace(/prooof/g, "proof")
    .replace(/uae climate /g, "uae climate")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const sources = readdirSync(SRC_DIR).filter((f) =>
  /\.(jpe?g|png)$/i.test(f),
);

if (!sources.length) {
  console.error("No source images found in", SRC_DIR);
  process.exit(1);
}

console.log(`Optimizing ${sources.length} images → ${OUT_DIR}\n`);

const manifest = {};
let totalIn = 0;
let totalOut = 0;

for (const file of sources) {
  const inPath = resolve(SRC_DIR, file);
  const slug = slugify(parse(file).name);
  const meta = await sharp(inPath).metadata();
  const inSize = (await sharp(inPath).toBuffer()).length;
  totalIn += inSize;

  // Determine which target widths apply (don't upscale)
  const widths = WIDTHS.filter((w) => w <= (meta.width || 1920));
  if (!widths.length) widths.push(meta.width || 1920);

  // Pre-rotate based on EXIF, strip metadata.
  const base = sharp(inPath).rotate().withMetadata({});

  let writtenForSlug = 0;
  for (const w of widths) {
    const webpName = `${slug}-${w}.webp`;
    const avifName = `${slug}-${w}.avif`;
    const webpOut = resolve(OUT_DIR, webpName);
    const avifOut = resolve(OUT_DIR, avifName);

    const webpInfo = await base
      .clone()
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY, effort: 6 })
      .toFile(webpOut);
    writtenForSlug += webpInfo.size;

    const avifInfo = await base
      .clone()
      .resize({ width: w, withoutEnlargement: true })
      .avif({ quality: AVIF_QUALITY, effort: 6 })
      .toFile(avifOut);
    writtenForSlug += avifInfo.size;
  }

  // Generate a tiny blur placeholder (16px wide, base64 data URL).
  const placeholderBuf = await base
    .clone()
    .resize({ width: BLUR_WIDTH })
    .webp({ quality: 30 })
    .toBuffer();
  const blurDataURL = `data:image/webp;base64,${placeholderBuf.toString("base64")}`;

  totalOut += writtenForSlug;

  manifest[slug] = {
    sources: widths.map((w) => ({
      width: w,
      webp: `/images/${slug}-${w}.webp`,
      avif: `/images/${slug}-${w}.avif`,
    })),
    aspectRatio:
      meta.width && meta.height ? meta.width / meta.height : 16 / 9,
    blurDataURL,
  };

  const inKB = (inSize / 1024).toFixed(0);
  const outKB = (writtenForSlug / 1024).toFixed(0);
  console.log(
    `  ${slug.padEnd(36)} ${String(meta.width).padStart(4)}×${meta.height}  in=${inKB}KB  out=${outKB}KB`,
  );
}

console.log(
  `\nTotal in: ${(totalIn / 1024 / 1024).toFixed(1)}MB  →  out: ${(totalOut / 1024 / 1024).toFixed(1)}MB  (saved ${(((totalIn - totalOut) / totalIn) * 100).toFixed(0)}%)`,
);

// Write manifest as a typed TS module
const manifestSrc = `// Auto-generated by scripts/optimize-images.mjs. Do not edit by hand.
// Run \`node scripts/optimize-images.mjs\` to regenerate.

export interface ImageSource {
  width: number;
  webp: string;
  avif: string;
}

export interface OptimizedImage {
  sources: ImageSource[];
  aspectRatio: number;
  blurDataURL: string;
}

export const IMAGES = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<
  string,
  OptimizedImage
>;

export type ImageKey = keyof typeof IMAGES;
`;

mkdirSync(parse(MANIFEST).dir, { recursive: true });
writeFileSync(MANIFEST, manifestSrc, "utf8");
console.log(`\nManifest written: ${MANIFEST}`);
